"""Create unified_signs table

Revision ID: b6bdb9966167
Revises: b8e32f57a640
Create Date: 2025-04-27 21:18:09.697724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6bdb9966167'
down_revision = 'b8e32f57a640'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unified_signs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid_gibdd', sa.Integer(), nullable=True),
    sa.Column('internal_id_comm', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('commercial_grade', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unified_signs')
    # ### end Alembic commands ###
