"""Initial migration

Revision ID: b8e32f57a640
Revises: 
Create Date: 2025-04-27 21:07:39.091504

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b8e32f57a640'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('road_sign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_id', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('unified_signs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unified_signs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uid_gibdd', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('internal_id_comm', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('latitude', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('longitude', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('commercial_grade', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.CheckConstraint('(commercial_grade >= 0) AND (commercial_grade <= 3)', name='unified_signs_commercial_grade_check'),
    sa.PrimaryKeyConstraint('id', name='unified_signs_pkey')
    )
    op.drop_table('road_sign')
    # ### end Alembic commands ###
